server:
  port: 8081

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

constants:
  host:
    remote-server: 127.0.0.1:8080

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 2000